"""
Reads all 3 school CSV files and generates a single SQL file for Supabase import.
Rules:
  - curriculum: pipe-separated → PostgreSQL text[]
  - status: always forced to 'active'
  - ON CONFLICT (slug) DO NOTHING
  - Produces inserted / skipped summary via DO block
"""

import csv
import os
import re

DATA_DIR = r"C:\Projects\Scholvisor\external data"
OUT_FILE = r"C:\Projects\Scholvisor\docs\import_schools.sql"

CSV_FILES = [
    "schools_extraction.csv",
    "Schools-KL_Full_Assets.CSV",
    "Schools-Selangor_Enriched.CSV",
]

NULLABLE_TEXT_COLS = {
    "address", "website_url", "curriculum", "age_range",
    "religious_environment", "summary", "school_level",
    "logo_url", "cover_image_url",
}


def esc(s: str) -> str:
    """Escape a string for SQL single-quoted literal."""
    return s.replace("'", "''")


def sql_text(val: str) -> str:
    if val.strip() == "":
        return "NULL"
    return f"'{esc(val.strip())}'"


def sql_curriculum(val: str) -> str:
    if val.strip() == "":
        return "ARRAY[]::text[]"
    parts = [p.strip() for p in val.split("|") if p.strip()]
    items = ", ".join(f"'{esc(p)}'" for p in parts)
    return f"ARRAY[{items}]"


def sql_int(val: str) -> str:
    try:
        return str(int(float(val.strip())))
    except (ValueError, TypeError):
        return "NULL"


rows = []
seen_slugs: set[str] = set()

for fname in CSV_FILES:
    path = os.path.join(DATA_DIR, fname)
    with open(path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            slug = row.get("slug", "").strip()
            if not slug:
                continue
            rows.append((fname, row))

total = len(rows)

lines = []
lines.append("-- =============================================================")
lines.append("-- Schools import — generated by generate_schools_sql.py")
lines.append(f"-- Source files: {', '.join(CSV_FILES)}")
lines.append(f"-- Total rows in CSVs: {total}")
lines.append("-- ON CONFLICT (slug) DO NOTHING — existing rows untouched")
lines.append("-- =============================================================")
lines.append("")

# Count before
lines.append("-- Row counts before insert")
lines.append("SELECT 'before' AS phase, status, count(*) FROM schools GROUP BY status;")
lines.append("")

# Track inserted vs skipped using a temp table approach
lines.append("-- ---- BEGIN IMPORT ----")
lines.append("")

# Deduplicate within the batch (same slug appearing in multiple files)
deduped: list[tuple[str, dict]] = []
slug_set: set[str] = set()
for fname, row in rows:
    slug = row["slug"].strip()
    if slug not in slug_set:
        slug_set.add(slug)
        deduped.append((fname, row))

skipped_within_batch = total - len(deduped)

lines.append(f"-- Unique slugs across all 3 files: {len(deduped)}")
if skipped_within_batch:
    lines.append(f"-- Duplicate slugs within batch (skipped): {skipped_within_batch}")
lines.append("")

# Generate INSERT with xmax trick to count inserted vs conflict
lines.append("""-- We use a CTE with INSERT RETURNING to distinguish inserted vs skipped.
-- xmax = 0 → freshly inserted row. xmax != 0 → conflict (skipped).
WITH inserted AS (
  INSERT INTO schools (
    name, slug, city, country, address, website_url,
    curriculum, age_range, religious_environment,
    price_min, price_max, summary, school_level,
    logo_url, cover_image_url, status
  )
  VALUES""")

value_lines = []
for fname, row in deduped:
    name              = sql_text(row.get("name", ""))
    slug              = sql_text(row.get("slug", ""))
    city              = sql_text(row.get("city", ""))
    country           = sql_text(row.get("country", ""))
    address           = sql_text(row.get("address", ""))
    website_url       = sql_text(row.get("website_url", ""))
    curriculum        = sql_curriculum(row.get("curriculum", ""))
    age_range         = sql_text(row.get("age_range", ""))
    religious_env     = sql_text(row.get("religious_environment", ""))
    price_min         = sql_int(row.get("price_min", ""))
    price_max         = sql_int(row.get("price_max", ""))
    summary           = sql_text(row.get("summary", ""))
    school_level      = sql_text(row.get("school_level", ""))
    logo_url          = sql_text(row.get("logo_url", ""))
    cover_image_url   = sql_text(row.get("cover_image_url", ""))
    # Always force active
    status            = "'active'"

    value_lines.append(
        f"    ({name}, {slug}, {city}, {country}, {address}, {website_url},\n"
        f"     {curriculum}, {age_range}, {religious_env},\n"
        f"     {price_min}, {price_max}, {summary}, {school_level},\n"
        f"     {logo_url}, {cover_image_url}, {status})"
    )

lines.append(",\n".join(value_lines))
lines.append("""  ON CONFLICT (slug) DO NOTHING
  RETURNING xmax
)
SELECT
  count(*) FILTER (WHERE xmax = 0)  AS inserted,
  count(*) FILTER (WHERE xmax != 0) AS conflict_skipped,
  (SELECT count(*) FROM schools)    AS total_schools_after
FROM inserted;""")

lines.append("")
lines.append("-- Row counts after insert")
lines.append("SELECT status, count(*) FROM schools GROUP BY status;")

sql = "\n".join(lines)

with open(OUT_FILE, "w", encoding="utf-8") as f:
    f.write(sql)

print(f"Written: {OUT_FILE}")
print(f"Total CSV rows   : {total}")
print(f"Unique slugs     : {len(deduped)}")
print(f"Intra-batch dups : {skipped_within_batch}")
